import type { LegalSectionDefinition } from "@/components/legal/legal-page";
import { legalConfig } from "./config";

export const privacySections: readonly LegalSectionDefinition[] = [
  { id: "privacy-introduction", title: "Introduction", content: <p>This Privacy Policy explains how Kizunia handles information in connection with its website, accounts, profiles, portfolios, projects, competition discovery, and related services. It describes current product behavior at a user-facing level and does not create features that are not currently available.</p> },
  { id: "information-we-collect", title: "Information We Collect", content: <><p><strong>Account and authentication information.</strong> Depending on how you use Kizunia, this can include your name, email address, username, display username, profile image, account and authentication identifiers, email-verification state, and information associated with an email/password or Google or GitHub sign-in.</p><p><strong>Profile and User Content.</strong> We process information you provide in profiles, portfolios, projects, descriptions, skills, education, experience, social links, achievements, competition information, project links, images, uploaded media, testimonials, and other content submitted through the Service.</p><p><strong>Session and technical information.</strong> Authentication sessions include information such as session expiry and, where supplied by the authentication flow, IP address and user-agent information. Kizunia may also process request, security, and troubleshooting information needed to operate and protect the Service.</p></> },
  { id: "location-information", title: "Location Information", content: <p>Kizunia can use a user-selected or search location to support competition discovery. Location features may use Google Places when configured by the application. The current product does not establish continuous device-location tracking, and this Policy should not be read as claiming that it occurs. The exact handling of location data should be confirmed as the location features evolve.</p> },
  { id: "how-we-use-information", title: "How We Use Information", content: <ul><li>create and manage accounts and authenticate users;</li><li>provide profiles, portfolios, projects, media, and other requested features;</li><li>display intentionally public profiles and User Content;</li><li>support competition discovery and location-based discovery;</li><li>operate, maintain, troubleshoot, and improve Kizunia;</li><li>protect the Service, prevent abuse or fraud, and investigate security issues; and</li><li>comply with law, respond to lawful requests, and enforce the Terms.</li></ul> },
  { id: "public-information", title: "Public Information", content: <p>When you intentionally make a profile, portfolio, project, achievement, competition claim, or other content public, it may be visible to other users and public visitors. Kizunia may organize and use public content in profiles, projects, discovery, recommendations, search, previews, project cards, feeds, achievement displays, and competition-related surfaces as described in the Terms. Do not publish information publicly if you do not want it accessed or redistributed.</p> },
  { id: "sharing-information", title: "Sharing Information", content: <p>We may share information with service providers and infrastructure providers that process it on Kizunia&apos;s behalf, including authentication, database, hosting, storage/media, location, security, and operational providers. We may also disclose information when required by law, to respond to legal process, protect rights and safety, prevent fraud or abuse, or support a merger, acquisition, financing, or transfer of all or part of the Service. We do not describe analytics providers here because the repository does not establish an analytics service.</p> },
  { id: "storage-providers", title: "Storage and Infrastructure Providers", content: <p>Uploaded identity and project assets are handled through Kizunia&apos;s storage abstraction. Cloudinary is the current storage adapter evidenced in the application, and may process asset metadata and files needed to store and deliver media. Kizunia may replace or add providers behind this abstraction; this Policy will be updated when that changes materially.</p> },
  { id: "cookies-similar-technologies", title: "Cookies and Similar Technologies", content: <p>Authentication uses session technologies, including cookies or similar mechanisms supplied by the authentication implementation, to keep users signed in and protect account flows. This page does not claim that Kizunia uses no cookies or tracking technologies, and Kizunia does not currently provide a cookie-preference center or consent-storage system. A dedicated audit is required to document exact cookie names, attributes, retention, and any non-essential technologies.</p> },
  { id: "security", title: "Security", content: <p>Kizunia uses reasonable technical and organizational measures intended to protect information, including access controls and provider safeguards. No method of transmission, storage, or security measure is perfect, and we cannot guarantee absolute security.</p> },
  { id: "retention", title: "Retention", content: <p>We retain information for as long as reasonably necessary to provide the Service, maintain accounts and records, protect security, prevent fraud and abuse, resolve disputes, enforce agreements, and meet legal obligations. Kizunia has not yet established a complete public schedule for every category of data, backup, soft-deleted record, or security record. We do not promise immediate permanent deletion from every system.</p> },
  { id: "privacy-rights", title: "Your Privacy Rights", content: <p>Depending on where you live and subject to applicable law, you may have rights to request access, correction, updating, deletion or erasure, restriction, portability, or information about processing, and to withdraw consent where processing is based on consent. You may contact Kizunia using the configured privacy contact to make a request. We do not currently provide a self-service privacy request or account-deletion workflow, and we may need to verify requests and apply lawful exceptions.</p> },
  { id: "account-data-deletion", title: "Account and Data Deletion", content: <p>Kizunia does not currently promise a self-service account deletion feature. Contact us about an applicable request using the privacy contact below. Any response may depend on verification, legal obligations, security needs, dispute resolution, backups, legal holds, and other lawful retention exceptions.</p> },
  { id: "childrens-privacy", title: "Children’s Privacy", content: <p>Kizunia is not intended for anyone who cannot legally agree to these Terms. We do not knowingly solicit information from children in violation of applicable law. If you believe a child has provided information improperly, contact Kizunia so the matter can be reviewed under applicable requirements.</p> },
  { id: "third-party-links", title: "Third-Party Links and Services", content: <p>Kizunia may link to competition websites, registration platforms, organizer sites, OAuth providers, and other third-party services. Their privacy practices are independent from Kizunia&apos;s. Review their policies before providing information or using those services.</p> },
  { id: "international-processing", title: "International Processing", content: <p>Kizunia uses external providers and infrastructure, but the repository does not establish a complete list of processing countries or transfer mechanisms. The applicable locations, safeguards, and provider terms must be confirmed before final publication of this Policy.</p> },
  { id: "privacy-changes", title: "Changes to This Policy", content: <p>We may update this Privacy Policy as Kizunia, its providers, or applicable law changes. Updates will be posted here with a revised Last Updated date. Your continued use after an update takes effect may constitute acceptance where permitted by law.</p> },
  { id: "privacy-contact", title: "Contact and Grievances", content: <p>Privacy contact: <strong>{legalConfig.privacyContactEmail}</strong>. Entity/controller: <strong>{legalConfig.entityName}</strong>. Address: <strong>{legalConfig.entityAddress}</strong>. A final privacy contact, grievance process, and legal entity must be supplied and reviewed before Kizunia relies on this Policy as its final notice.</p> },
];
