import type { LegalSectionDefinition } from "@/components/legal/legal-page";
import { legalConfig } from "./config";

export const termsSections: readonly LegalSectionDefinition[] = [
  { id: "acceptance", title: "Acceptance of Terms", content: <p>By accessing or using Kizunia, you agree to these Terms of Service and the Privacy Policy. If you do not agree, do not use the Service. These Terms apply to the website, features, and services provided by Kizunia.</p> },
  { id: "eligibility", title: "Eligibility", content: <p>You may use Kizunia only if you can form a legally binding agreement and are not prohibited from using the Service under applicable law. If you use Kizunia on behalf of another person or organization, you represent that you have authority to accept these Terms for them. Parents or guardians are responsible for supervising use by anyone who is not legally able to agree to these Terms.</p> },
  { id: "accounts", title: "Accounts and Security", content: <><p>Some features require an account. You must provide information that is accurate and keep it current. You are responsible for activity under your account, for safeguarding your credentials, and for promptly reporting suspected unauthorized access.</p><p>Do not impersonate another person, create an account using misleading information, or access an account without authorization. Kizunia is not responsible for losses caused by credentials that you fail to protect.</p></> },
  { id: "user-content", title: "User Content", content: <><p>User Content includes profiles, portfolio information, projects, descriptions, achievements, competition information, links, images, uploaded media, and other material you submit or make available through Kizunia.</p><p>You retain ownership of User Content to the extent you own the underlying rights. You are responsible for ensuring that you have all rights, permissions, and consents needed to submit it and for ensuring that it is accurate and lawful.</p></> },
  { id: "public-private-content", title: "Public and Private Content", content: <p>Kizunia supports content with different visibility settings. Content you intentionally make public may be visible to other users and public visitors. Restricted content is intended to be available only to the audiences permitted by the relevant feature. No setting should be treated as an absolute guarantee of confidentiality, so do not publish information publicly if you do not want it accessed or redistributed.</p> },
  { id: "public-content-license", title: "License to Public User Content", content: <><p>When you intentionally make User Content public, you grant Kizunia a non-exclusive, worldwide, royalty-free license, for the duration reasonably necessary to operate the Service, to host, store, reproduce, display, perform, distribute, communicate, format, technically adapt, create previews, thumbnails, or excerpts of, make available, promote, and otherwise use that public content as reasonably necessary to operate, maintain, improve, provide, and promote Kizunia.</p><p>This license supports public profiles, portfolio and project pages, discovery, search, recommendations, project cards, previews, feeds, competition-related displays, homepage and discovery features, and other Kizunia interfaces. Service providers acting on Kizunia&apos;s behalf may process public content where necessary to provide these functions. This license does not transfer ownership of your User Content to Kizunia.</p></> },
  { id: "public-achievements", title: "Public Achievements and Competition Claims", content: <p>If you publicly represent that you won or participated in a competition, received an award, completed a project, or achieved something else, Kizunia may organize, display, surface, recommend, summarize, or otherwise present that public User Content in relevant areas of the Service. Unless Kizunia expressly states that it has verified a claim, Kizunia should not be understood to have independently verified it.</p> },
  { id: "acceptable-use", title: "User Responsibilities and Acceptable Use", content: <><p>You may not use Kizunia to:</p><ul><li>break the law, infringe rights, commit fraud, or impersonate someone;</li><li>harass, abuse, threaten, or exploit others;</li><li>upload malicious software or attack, probe, disrupt, or gain unauthorized access to systems;</li><li>bypass access controls, rate limits, or other protective measures;</li><li>scrape or automatically collect information except as expressly permitted by Kizunia; or</li><li>misuse APIs, automated systems, or the Service in a way that interferes with its operation or places unreasonable load on it.</li></ul></> },
  { id: "competition-information", title: "Competition Information", content: <p>Kizunia may display competition information obtained from users, organizers, third-party sources, or other sources. It may be inaccurate, incomplete, outdated, changed, postponed, cancelled, or unavailable. Unless expressly stated otherwise, Kizunia does not guarantee that competition information is complete, current, accurate, or officially endorsed. Verify important details, deadlines, eligibility rules, and registration requirements with the official organizer.</p> },
  { id: "third-party-services", title: "Third-Party Services and Links", content: <p>Kizunia may link to or work with external competition websites, registration platforms, organizer websites, authentication providers, storage providers, infrastructure providers, and other third-party services. Those services operate under their own terms and privacy policies. Kizunia is not responsible for third-party content, availability, security, or practices.</p> },
  { id: "kizunia-intellectual-property", title: "Kizunia Intellectual Property", content: <p>Kizunia and its licensors retain rights in the Service, including its software, branding, logos, trademarks, user interface, design, original content, and documentation. Except for the rights expressly granted in these Terms, no rights are granted to you. These Terms do not claim ownership of User Content.</p> },
  { id: "feedback", title: "Feedback", content: <p>If you provide suggestions, ideas, or other feedback about Kizunia, you allow Kizunia to use it for product development and improvement without restriction or payment, subject to applicable law. Feedback does not include your User Content.</p> },
  { id: "suspension-termination", title: "Suspension and Termination", content: <p>Kizunia may suspend, restrict, disable, or terminate an account or feature where reasonably necessary to enforce these Terms, protect users or Kizunia, prevent abuse or fraud, address security threats, investigate suspected violations, comply with law or legal requests, or address material risk to the Service. Where appropriate and practicable, Kizunia may provide notice or an opportunity to resolve an issue.</p> },
  { id: "termination-consequences", title: "Consequences of Termination", content: <p>After suspension or termination, you may lose access to your account, User Content, or features. Kizunia may retain information where reasonably necessary for legal compliance, security, fraud prevention, dispute resolution, enforcement, or legitimate operational purposes. Kizunia does not promise immediate permanent removal from every backup, cache, or system.</p> },
  { id: "availability", title: "Service Availability and Changes", content: <p>The Service may experience downtime, maintenance, bugs, interruptions, or changes. Kizunia may modify, suspend, remove, or discontinue features, including without advance notice where reasonably necessary. We do not guarantee uninterrupted or error-free availability.</p> },
  { id: "disclaimer", title: "Disclaimer of Warranties", content: <p>To the maximum extent permitted by applicable law, Kizunia is provided on an “as is” and “as available” basis, without warranties of any kind, express or implied. This includes no guarantee that the Service or competition information will be uninterrupted, secure, accurate, complete, or free of errors. Nothing in these Terms excludes a warranty or right that cannot legally be excluded.</p> },
  { id: "limitation-of-liability", title: "Limitation of Liability", content: <p>To the maximum extent permitted by applicable law, Kizunia and its people and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or loss of data, profits, opportunities, or goodwill, arising from or related to the Service or these Terms. This does not limit liability that cannot legally be limited.</p> },
  { id: "indemnification", title: "Indemnification", content: <p>To the extent permitted by applicable law, you agree to defend, indemnify, and hold harmless Kizunia and its people and service providers from claims, losses, liabilities, and expenses arising from your violation of these Terms, your User Content, your violation of a third party&apos;s rights, your unlawful use of the Service, or your misuse of Kizunia.</p> },
  { id: "changes", title: "Changes to These Terms", content: <p>Kizunia may update these Terms as the Service or applicable law changes. The updated Terms will be posted on this page with a revised Last Updated date. Your continued use after an update takes effect constitutes acceptance of the updated Terms, to the extent permitted by law.</p> },
  { id: "governing-law", title: "Governing Law and Jurisdiction", content: <p>The governing law for these Terms is currently <strong>{legalConfig.governingLaw}</strong>. The applicable courts or jurisdiction are currently <strong>{legalConfig.jurisdiction}</strong>. These values must be confirmed by Kizunia&apos;s legal advisers and entity owners before these Terms are relied on as final.</p> },
  { id: "contact", title: "Contact", content: <p>Legal contact: <strong>{legalConfig.legalContactEmail}</strong>. Entity: <strong>{legalConfig.entityName}</strong>. Address: <strong>{legalConfig.entityAddress}</strong>. These values are intentionally shown as not yet configured until Kizunia supplies verified legal information.</p> },
];
