import { z } from "zod";

/** Place autocomplete against the external provider (admin, billed). */
export const PlaceAutocompleteQuerySchema = z.object({
  q: z
    .string()
    .trim()
    .min(2, "Search query must be at least 2 characters.")
    .max(200, "Search query cannot exceed 200 characters."),

  limit: z.coerce.number().int().min(1).max(20).default(10),

  /**
   * Groups a run of keystrokes plus the final details call into one billed
   * session. Opaque to Kizunia — generated by the client, passed straight
   * through.
   */
  sessionToken: z.string().trim().max(100).optional(),
});

export type PlaceAutocompleteQuery = z.infer<typeof PlaceAutocompleteQuerySchema>;

/**
 * Upper bound on a provider place id.
 *
 * Google's ids are typically well under 200 characters, but the format is
 * explicitly documented as opaque and subject to change, so this is a sanity
 * ceiling rather than a specification. It exists to stop a multi-kilobyte
 * value being forwarded to a billed endpoint, not to predict the provider.
 */
const MAX_PLACE_ID_LENGTH = 512;

/**
 * Printable ASCII with no spaces.
 *
 * Deliberately not a Google-shaped pattern. The provider does not guarantee a
 * charset, so a tight regex would be a future outage the first time an id
 * contains something unexpected. This rejects what an opaque token can never
 * legitimately be — whitespace, control characters, non-ASCII — and leaves the
 * rest to the provider, which is the authority on whether an id resolves.
 */
const PLACE_ID_PATTERN = /^[\x21-\x7E]+$/;

/**
 * A provider place id arriving from a URL.
 *
 * Validated because `placeId` is user-controlled and reaches a billed provider
 * call, while every other user input on that path is already schema-checked.
 * An id rejected here costs nothing; one forwarded blindly costs a lookup.
 */
export const PlaceIdSchema = z
  .string()
  .trim()
  .min(1, "A place id is required.")
  .max(
    MAX_PLACE_ID_LENGTH,
    `A place id cannot exceed ${MAX_PLACE_ID_LENGTH} characters.`,
  )
  .regex(PLACE_ID_PATTERN, "That place id is not in a usable format.");

/** Typeahead over search areas the platform already knows (public, free). */
export const SearchAreaQuerySchema = z.object({
  q: z
    .string()
    .trim()
    .min(2, "Search query must be at least 2 characters.")
    .max(200, "Search query cannot exceed 200 characters."),

  limit: z.coerce.number().int().min(1).max(20).default(10),
});

export type SearchAreaQuery = z.infer<typeof SearchAreaQuerySchema>;
