packages:
  - .
allowBuilds:
  '@prisma/engines': true
  '@tsparticles/engine': false
  prisma: true
  sharp: false
  unrs-resolver: false
  '@prisma/client': true
  esbuild: false
  '@firebase/util': false
  protobufjs: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
