export const PortfolioErrorCode = {
  NOT_FOUND: "PORTFOLIO_NOT_FOUND",

  ALREADY_EXISTS: "PORTFOLIO_ALREADY_EXISTS",

  /** A soft-deleted portfolio blocks creating another: restore it instead. */
  DELETED: "PORTFOLIO_DELETED",

  /** Restore was requested for a portfolio that is not deleted. */
  NOT_DELETED: "PORTFOLIO_NOT_DELETED",

  PROJECT_ALREADY_EXISTS: "PORTFOLIO_PROJECT_ALREADY_EXISTS",

  PROJECT_NOT_FOUND: "PORTFOLIO_PROJECT_NOT_FOUND",

  PROJECT_MEMBERSHIP_REQUIRED: "PORTFOLIO_PROJECT_MEMBERSHIP_REQUIRED",

  PROJECT_REORDER_MISMATCH: "PORTFOLIO_PROJECT_REORDER_MISMATCH",

  TESTIMONIAL_NOT_FOUND: "PORTFOLIO_TESTIMONIAL_NOT_FOUND",

  TESTIMONIAL_REORDER_MISMATCH: "PORTFOLIO_TESTIMONIAL_REORDER_MISMATCH",

  TECHNOLOGY_ALREADY_EXISTS: "PORTFOLIO_TECHNOLOGY_ALREADY_EXISTS",

  TECHNOLOGY_NOT_FOUND: "PORTFOLIO_TECHNOLOGY_NOT_FOUND",

  TECHNOLOGY_REORDER_MISMATCH: "PORTFOLIO_TECHNOLOGY_REORDER_MISMATCH",
} as const;

export type PortfolioErrorCode =
  (typeof PortfolioErrorCode)[keyof typeof PortfolioErrorCode];
