export const ProjectErrorCode = {
  NOT_FOUND: "PROJECT_NOT_FOUND",
  DUPLICATE_SLUG: "PROJECT_DUPLICATE_SLUG",
  DELETED: "PROJECT_DELETED",
  LINK_NOT_FOUND: "PROJECT_LINK_NOT_FOUND",
  LINK_REORDER_MISMATCH: "PROJECT_LINK_REORDER_MISMATCH",
  TESTIMONIAL_NOT_FOUND: "PROJECT_TESTIMONIAL_NOT_FOUND",
  TESTIMONIAL_REORDER_MISMATCH: "PROJECT_TESTIMONIAL_REORDER_MISMATCH",
  TECHNOLOGY_NOT_FOUND: "PROJECT_TECHNOLOGY_NOT_FOUND",
  TECHNOLOGY_ALREADY_ATTACHED: "PROJECT_TECHNOLOGY_ALREADY_ATTACHED",
  TECHNOLOGY_REORDER_MISMATCH: "PROJECT_TECHNOLOGY_REORDER_MISMATCH",
} as const;

export type ProjectErrorCode =
  (typeof ProjectErrorCode)[keyof typeof ProjectErrorCode];