export enum PlatformAction {
  CREATE_COMPETITION = "CREATE_COMPETITION",
  EDIT_COMPETITIONS = "EDIT_COMPETITION",
  VIEW_ALL_COMPETITIONS = "VIEW_ALL_COMPETITIONS",
  // Automatic lifecycle status management: previewing/applying reconciliation
  // and toggling `automaticStatusUpdatesDisabled`. Distinct from
  // EDIT_COMPETITIONS — it governs the automation surface, not ordinary field
  // edits, which stay gated by the existing per-resource CompetitionAction.EDIT.
  MANAGE_COMPETITION_LIFECYCLE = "MANAGE_COMPETITION_LIFECYCLE",
  MANAGE_USERS = "MANAGE_USERS",

  ACCESS_ADMIN_DASHBOARD = "ACCESS_ADMIN_DASHBOARD",

  // Users
  VIEW_ALL_USERS = "VIEW_ALL_USERS",

  // Projects
  VIEW_PUBLIC_PROJECTS = "VIEW_PUBLIC_PROJECTS",
  VIEW_ALL_PROJECTS = "VIEW_ALL_PROJECTS",
  CREATE_PROJECT = "CREATE_PROJECT",

  // Blogs
  VIEW_ALL_BLOGS = "VIEW_ALL_BLOGS",
  CREATE_BLOG = "CREATE_BLOG",

  // Portfolios
  VIEW_ALL_PORTFOLIOS = "VIEW_ALL_PORTFOLIOS",
  CREATE_PORTFOLIO = "CREATE_PORTFOLIO",

  // Suggestions / Moderation
  VIEW_COMPETITION_SUGGESTIONS = "VIEW_COMPETITION_SUGGESTIONS",
  CREATE_COMPETITION_SUGGESTION = "CREATE_COMPETITION_SUGGESTION",
  REVIEW_COMPETITION_SUGGESTIONS = "REVIEW_COMPETITION_SUGGESTIONS",

  VIEW_PROJECT_SUGGESTIONS = "VIEW_PROJECT_SUGGESTIONS",
  REVIEW_PROJECT_SUGGESTIONS = "REVIEW_PROJECT_SUGGESTIONS",

  VIEW_BLOG_SUGGESTIONS = "VIEW_BLOG_SUGGESTIONS",
  REVIEW_BLOG_SUGGESTIONS = "REVIEW_BLOG_SUGGESTIONS",

  // Taxonomy
  MANAGE_CATEGORIES = "MANAGE_CATEGORIES",
  MANAGE_TECHNOLOGIES = "MANAGE_TECHNOLOGIES",
  MANAGE_TAGS = "MANAGE_TAGS",

  // Assets
  MANAGE_MEDIA = "MANAGE_MEDIA",

  // Site
  MANAGE_SITE_SETTINGS = "MANAGE_SITE_SETTINGS",
  VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS",
}
